# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '7.x'  # Specify the .NET SDK version compatible with your project
      installationPath: $(Agent.ToolsDirectory)/dotnet

      
  - script: dotnet restore --ignore-failed-sources --verbosity detailed
    displayName: 'Restore NuGet Packages (Debug Mode)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: '**/*.sln'  # Builds all solution files
      arguments: '--configuration $(buildConfiguration)'
      
  
  # **Start MongoDB in Docker**
  - script: |
      docker run -d --name mongodb -p 27017:27017 mongo:latest
    displayName: 'Start MongoDB in Docker'

  # **Wait for MongoDB to Start **
  - script: |
      sleep 10  # Wait 10 seconds to make sure MongoDB is up
    displayName: 'Wait for MongoDB to be Ready'

  - script: |
      nc -zv localhost 27017
    displayName: 'Check MongoDB Connection'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.IntegrationTests.csproj'  # Runs tests for all test projects
      arguments: '--configuration $(buildConfiguration) --logger trx --results-directory $(Agent.TempDirectory)/TestResults --verbosity detailed'





