# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '7.x'  # Specify the .NET SDK version compatible with your project
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: dotnet restore --ignore-failed-sources --verbosity detailed
    displayName: 'Restore NuGet Packages (Debug Mode)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: '**/*.sln'  # Builds all solution files
      arguments: '--configuration $(buildConfiguration)'

  # **Start MongoDB in Docker**
  - script: |
      docker run -d --name mongodb -p 27017:27017 mongo:latest
    displayName: 'Start MongoDB in Docker'

  - script: |
      echo "Waiting for MongoDB to be fully ready..."
      for i in {1..30}; do
        nc -zv localhost 27017 && echo "MongoDB is up!" && exit 0
        echo "Waiting..."
        sleep 2
      done
      echo "MongoDB did not start in time" && exit 1
    displayName: 'Wait for MongoDB (Improved)'

  # **MongoDB Debugging**
  - script: |
      docker exec mongodb mongosh --eval "db.runCommand({ ping: 1 })"
    displayName: 'Debug: MongoDB Ping Test'

  - script: |
      docker exec mongodb mongosh --eval "show dbs"
      docker exec mongodb mongosh --eval "use testdb; show collections"
    displayName: 'Debug: Check MongoDB State'

  # **Debug: List All .csproj Files**
  - script: find $(System.DefaultWorkingDirectory) -name "*.csproj"
    displayName: 'Debug: List all .csproj files'

  - script: |
      echo "Verifying default image..."
      ls -lah $(System.DefaultWorkingDirectory)/ProjectMongoDB.IntegrationTests/wwwroot
    displayName: 'Debug: Check Default Image'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '**/*.IntegrationTests.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '$(Agent.TempDirectory)/TestResults/*.trx'
      mergeTestResults: true
      failTaskOnFailedTests: true





