# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      version: '7.x'  # Specify the .NET SDK version compatible with your project
      installationPath: $(Agent.ToolsDirectory)/dotnet

      
  - script: dotnet restore --ignore-failed-sources --verbosity detailed
    displayName: 'Restore NuGet Packages (Debug Mode)'

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: '**/*.sln'  # Builds all solution files
      arguments: '--configuration $(buildConfiguration)'
      
  
  # **Start MongoDB in Docker**
  - script: |
      docker run -d --name mongodb -p 27017:27017 mongo:latest
    displayName: 'Start MongoDB in Docker'

  # **Wait for MongoDB to Start **
  - script: |
      for i in {1..30}; do # Try 30 times
        nc -zv localhost 27017 && break
        sleep 1
      done
      if [[ $i -eq 31 ]]; then
        echo "Failed to connect to MongoDB after 30 attempts"
        exit 1
      fi
    displayName: 'Check MongoDB Connection with Retry'

  - task: DotNetCoreCLI@2
    displayName: 'Run Tests'
    inputs:
      command: 'test'
      projects: '/home/vsts/work/1/s/ProjectMongoDB.IntegrationTests/ProjectMongoDB.IntegrationTests.csproj' # Explicit path  # Runs tests for all test projects
      arguments: '--logger trx --results-directory $(Agent.TempDirectory)/TestResults --configuration Release --verbosity detailed'





